Instala as Bibliotecas

In [ ]:
pip install pandas

In [ ]:
pip install sqlalchemy

In [ ]:
pip install psycopg2

Importar as Bibliotecas

In [39]:
import pandas as pd
pd.set_option("display.max_colwidth", 150)
pd.set_option("display.min_rows", 20)

from sqlalchemy import create_engine

Definir função para buscar os Dados

In [7]:
def busca_titulos_tesouro_direto():
    url = 'https://www.tesourotransparente.gov.br/ckan/dataset/df56aa42-484a-4a59-8184-7676580c81e3/resource/796d2059-14e9-44e3-80c9-2d9e30b405c1/download/PrecoTaxaTesouroDireto.csv'
    df = pd.read_csv(url, sep=';', decimal=',')
    df['Data Vencimento'] = pd.to_datetime(df['Data Vencimento'], dayfirst=True)
    df['Data Base'] = pd.to_datetime(df['Data Base'], dayfirst=True)
    multi_indice = pd.MultiIndex.from_frame(df.iloc[:,:3])
    df = df.set_index(multi_indice).iloc[:, 3:]
    return df

Busca os títulos do Tesouro Direto

In [ ]:
titulos = busca_titulos_tesouro_direto()

Busca somente os Préfixados

In [ ]:
prefixado = titulos.loc[('Tesouro Prefixado')]
prefixado['Tipo'] = "PRE-FIXADOS"

In [59]:
prefixado

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
2016-01-01      2014-02-19              12.08             12.13
2017-01-01      2014-02-19              12.59             12.65
2018-01-01      2014-02-19              12.85             12.91
2015-01-01      2014-02-18              11.31             11.35
2016-01-01      2014-02-18              12.21             12.26
2017-01-01      2014-02-18              12.68             12.74
2018-01-01      2014-02-18              12.92             12.98
2016-01-01      2014-02-17              12.34             12.39
2018-01-01      2014-02-17              13.02             13.08
2017-01-01      2014-02-17              12.79             12.85
...                                       ...               ...
2014-01-01      2011-11-21              10.33             10.39
2015-01-01      2011-11-21              10.66             10.72
2012-01-01      2011-11-18              11.06             11.09
2013-01-01      2011-11-18              10.01             10.05
2014-01-01      2011-11-18              10.33             10.39
2015-01-01      2011-11-18              10.70             10.76
                2011-11-17              10.76             10.82
2014-01-01      2011-11-17              10.38             10.44
2013-01-01      2011-11-17              10.02             10.06
2012-01-01      2011-11-17              11.07             11.10

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
2016-01-01      2014-02-19           809.13          808.46         808.09
2017-01-01      2014-02-19           712.95          711.87         711.53
2018-01-01      2014-02-19           628.53          627.24         626.94
2015-01-01      2014-02-18           911.08          910.80         910.41
2016-01-01      2014-02-18           807.02          806.35         805.98
2017-01-01      2014-02-18           710.99          709.91         709.57
2018-01-01      2014-02-18           626.73          625.45         625.15
2016-01-01      2014-02-17           804.91          804.24         803.87
2018-01-01      2014-02-17           624.30          623.02         622.72
2017-01-01      2014-02-17           708.67          707.59         707.25
...                                     ...             ...            ...
2014-01-01      2011-11-21           812.26          811.33         811.01
2015-01-01      2011-11-21           729.10          727.87         727.58
2012-01-01      2011-11-18           987.58          987.55         987.14
2013-01-01      2011-11-18           899.08          898.71         898.37
2014-01-01      2011-11-18           811.95          811.01         810.69
2015-01-01      2011-11-18           727.99          726.76         726.46
                2011-11-17           726.46          725.23         724.94
2014-01-01      2011-11-17           810.85          809.91         809.60
2013-01-01      2011-11-17           898.65          898.28         897.94
2012-01-01      2011-11-17           987.16          987.13         986.72

                                   Tipo
Data Vencimento Data Base
2016-01-01      2014-02-19  PRE-FIXADOS
2017-01-01      2014-02-19  PRE-FIXADOS
2018-01-01      2014-02-19  PRE-FIXADOS
2015-01-01      2014-02-18  PRE-FIXADOS
2016-01-01      2014-02-18  PRE-FIXADOS
2017-01-01      2014-02-18  PRE-FIXADOS
2018-01-01      2014-02-18  PRE-FIXADOS
2016-01-01      2014-02-17  PRE-FIXADOS
2018-01-01      2014-02-17  PRE-FIXADOS
2017-01-01      2014-02-17  PRE-FIXADOS
...                                 ...
2014-01-01      2011-11-21  PRE-FIXADOS
2015-01-01      2011-11-21  PRE-FIXADOS
2012-01-01      2011-11-18  PRE-FIXADOS
2013-01-01      2011-11-18  PRE-FIXADOS
2014-01-01      2011-11-18  PRE-FIXADOS
2015-01-01      2011-11-18  PRE-FIXADOS
                2011-11-17  PRE-FIXADOS
2014-01-01      2011-11-17  PRE-FIXADOS
2013-01-01      2011-11-17  PRE-FIXADOS
2012-01-01      2011-11-17  PRE-FIXADOS

[24327 rows x 6 columns]

Busca os IPCAs

In [60]:
ipca = titulos.loc[('Tesouro IPCA+')]
ipca['Tipo'] = "IPCA"

C:\Users\jpaul\AppData\Local\Temp\ipykernel_12916\3738600803.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ipca['Tipo'] = "IPCA"

In [61]:
ipca

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
2015-05-15      2014-02-19               4.71              4.73
2019-05-15      2014-02-19               6.26              6.32
2035-05-15      2014-02-19               6.92              7.02
2024-08-15      2014-02-19               6.74              6.82
                2014-02-18               6.79              6.87
2019-05-15      2014-02-18               6.37              6.43
2035-05-15      2014-02-18               6.95              7.05
2015-05-15      2014-02-18               4.86              4.88
2024-08-15      2014-02-17               6.82              6.90
2035-05-15      2014-02-17               6.98              7.08
...                                       ...               ...
2024-08-15      2012-02-07               5.61              5.69
                2011-11-22               5.50              5.58
2035-05-15      2011-11-22               5.55              5.65
2015-05-15      2011-11-22               4.99              5.03
2024-08-15      2011-11-21               5.48              5.56
2015-05-15      2011-11-21               4.96              5.00
2035-05-15      2011-11-21               5.55              5.65
2024-08-15      2011-11-18               5.50              5.58
2015-05-15      2011-11-18               4.95              4.99
2035-05-15      2011-11-18               5.57              5.67

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
2015-05-15      2014-02-19          2248.65         2248.13        2247.20
2019-05-15      2014-02-19          1735.30         1730.22        1729.40
2035-05-15      2014-02-19           577.89          566.58         566.29
2024-08-15      2014-02-19          1204.24         1194.86        1194.28
                2014-02-18          1197.78         1188.45        1187.87
2019-05-15      2014-02-18          1725.18         1720.13        1719.31
2035-05-15      2014-02-18           574.18          562.95         562.67
2015-05-15      2014-02-18          2243.78         2243.26        2242.31
2024-08-15      2014-02-17          1193.69         1184.39        1183.80
2035-05-15      2014-02-17           570.50          559.34         559.06
...                                     ...             ...            ...
2024-08-15      2012-02-07          1072.09         1062.02        1061.59
                2011-11-22          1059.37         1049.24        1048.84
2035-05-15      2011-11-22           590.46          577.52         577.30
2015-05-15      2011-11-22          1764.46         1762.13        1761.50
2024-08-15      2011-11-21          1061.52         1051.36        1050.96
2015-05-15      2011-11-21          1765.58         1763.25        1762.61
2035-05-15      2011-11-21           590.24          577.30         577.08
2024-08-15      2011-11-18          1058.57         1048.43        1047.69
2015-05-15      2011-11-18          1765.53         1763.20        1761.98
2035-05-15      2011-11-18           587.40          574.53         574.12

                            Tipo
Data Vencimento Data Base
2015-05-15      2014-02-19  IPCA
2019-05-15      2014-02-19  IPCA
2035-05-15      2014-02-19  IPCA
2024-08-15      2014-02-19  IPCA
                2014-02-18  IPCA
2019-05-15      2014-02-18  IPCA
2035-05-15      2014-02-18  IPCA
2015-05-15      2014-02-18  IPCA
2024-08-15      2014-02-17  IPCA
2035-05-15      2014-02-17  IPCA
...                          ...
2024-08-15      2012-02-07  IPCA
                2011-11-22  IPCA
2035-05-15      2011-11-22  IPCA
2015-05-15      2011-11-22  IPCA
2024-08-15      2011-11-21  IPCA
2015-05-15      2011-11-21  IPCA
2035-05-15      2011-11-21  IPCA
2024-08-15      2011-11-18  IPCA
2015-05-15      2011-11-18  IPCA
2035-05-15      2011-11-18  IPCA

[14864 rows x 6 columns]

In [62]:
frames = [prefixado, ipca]
todos = pd.concat(frames)

In [63]:
todos

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
2016-01-01      2014-02-19              12.08             12.13
2017-01-01      2014-02-19              12.59             12.65
2018-01-01      2014-02-19              12.85             12.91
2015-01-01      2014-02-18              11.31             11.35
2016-01-01      2014-02-18              12.21             12.26
2017-01-01      2014-02-18              12.68             12.74
2018-01-01      2014-02-18              12.92             12.98
2016-01-01      2014-02-17              12.34             12.39
2018-01-01      2014-02-17              13.02             13.08
2017-01-01      2014-02-17              12.79             12.85
...                                       ...               ...
2024-08-15      2012-02-07               5.61              5.69
                2011-11-22               5.50              5.58
2035-05-15      2011-11-22               5.55              5.65
2015-05-15      2011-11-22               4.99              5.03
2024-08-15      2011-11-21               5.48              5.56
2015-05-15      2011-11-21               4.96              5.00
2035-05-15      2011-11-21               5.55              5.65
2024-08-15      2011-11-18               5.50              5.58
2015-05-15      2011-11-18               4.95              4.99
2035-05-15      2011-11-18               5.57              5.67

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
2016-01-01      2014-02-19           809.13          808.46         808.09
2017-01-01      2014-02-19           712.95          711.87         711.53
2018-01-01      2014-02-19           628.53          627.24         626.94
2015-01-01      2014-02-18           911.08          910.80         910.41
2016-01-01      2014-02-18           807.02          806.35         805.98
2017-01-01      2014-02-18           710.99          709.91         709.57
2018-01-01      2014-02-18           626.73          625.45         625.15
2016-01-01      2014-02-17           804.91          804.24         803.87
2018-01-01      2014-02-17           624.30          623.02         622.72
2017-01-01      2014-02-17           708.67          707.59         707.25
...                                     ...             ...            ...
2024-08-15      2012-02-07          1072.09         1062.02        1061.59
                2011-11-22          1059.37         1049.24        1048.84
2035-05-15      2011-11-22           590.46          577.52         577.30
2015-05-15      2011-11-22          1764.46         1762.13        1761.50
2024-08-15      2011-11-21          1061.52         1051.36        1050.96
2015-05-15      2011-11-21          1765.58         1763.25        1762.61
2035-05-15      2011-11-21           590.24          577.30         577.08
2024-08-15      2011-11-18          1058.57         1048.43        1047.69
2015-05-15      2011-11-18          1765.53         1763.20        1761.98
2035-05-15      2011-11-18           587.40          574.53         574.12

                                   Tipo
Data Vencimento Data Base
2016-01-01      2014-02-19  PRE-FIXADOS
2017-01-01      2014-02-19  PRE-FIXADOS
2018-01-01      2014-02-19  PRE-FIXADOS
2015-01-01      2014-02-18  PRE-FIXADOS
2016-01-01      2014-02-18  PRE-FIXADOS
2017-01-01      2014-02-18  PRE-FIXADOS
2018-01-01      2014-02-18  PRE-FIXADOS
2016-01-01      2014-02-17  PRE-FIXADOS
2018-01-01      2014-02-17  PRE-FIXADOS
2017-01-01      2014-02-17  PRE-FIXADOS
...                                 ...
2024-08-15      2012-02-07         IPCA
                2011-11-22         IPCA
2035-05-15      2011-11-22         IPCA
2015-05-15      2011-11-22         IPCA
2024-08-15      2011-11-21         IPCA
2015-05-15      2011-11-21         IPCA
2035-05-15      2011-11-21         IPCA
2024-08-15      2011-11-18         IPCA
2015-05-15      2011-11-18         IPCA
2035-05-15      2011-11-18         IPCA

[39191 rows x 6 columns]

Grava os dados no Banco de Dados

In [51]:
connection_string = "postgresql://postgres:Jp1987@localhost:5432/postgres"

In [64]:
engine = create_engine(connection_string)

In [65]:
todos.to_sql("dados_tesouro", con=engine, if_exists="append", index=False)

191